---
title: "nCov202004"
author: "lhj"
date: "6/18/2020"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Sequencing Statistics of Depth
```{r Fig1b_Depth,fig.width=20,fig.height=8}
      DepthDATA      <- read.table("../results/Fig1b-allSamples.depth.txt", header=TRUE)
      posi <- DepthDATA$posi
        dep1_4 <- DepthDATA$dep1_4
        dep1_2 <- DepthDATA$dep1_2
        dep3_4 <- DepthDATA$dep3_4
        
        dep1_4_log10 <- log(dep1_4+1,10)
        dep1_2_log10 <- log(dep1_2+1,10)
        dep3_4_log10 <- log(dep3_4+1,10)
  
        out_tu <- paste("./outFigures/Fig1b-allSamples.depth.pdf", sep = "") 
  
        ggplot(DepthDATA,aes(x = posi, y = dep1_2_log10)) + #ylim(0,5)+
           geom_ribbon(aes(ymin=dep1_4_log10, ymax=dep3_4_log10, x=posi), fill = "grey", alpha = 0.8) + 
           geom_line(size = 1.3) +
      
           ylab("Sequencing Depth (Log)") + xlab('') + 
           
           scale_x_continuous(labels = NULL,expand = c(0,0)) +
           theme_bw()+ 
           theme(axis.text.y=element_text(family="Times",size=24,face="plain"), 
            axis.title.y=element_text(family="Times",size = 24,face="plain"), 
           panel.grid.major = element_blank(),panel.grid.minor = element_blank(),panel.background = 		element_blank(),panel.border = element_blank()) +  
           
         ggsave(out_tu,width = 26,height = 8)

```



#Statistic of Genome Coverage VS Ct value 
```{r,fig.width=20,fig.height=8}
          data_file <- paste("../results/Fig1c-CoverageVSCt.txt",sep = "")
          print(data_file)
          DATA <- read.table(data_file,sep = '\t',header = TRUE)
          Ct <- DATA$Ct
          Ct <- as.numeric(as.character(Ct))
          perct_10X <- DATA$Cov10X
          out_tu <- paste("./outFigures/Fig1c-CoverageVSCt.pdf", sep = "") 
          sample <-DATA$sample
          P <- ggplot(DATA,aes(x=Ct,y=perct_10X)) +
            geom_point() + ylab("Coverage(%)")+xlab("Ct value") +   ylim(0,100) +    
            theme_bw()+  
            theme( axis.text.x=element_text(colour="black",family="Times",size=14,angle = 90, hjust = 1), 
                   axis.text.y=element_text(family="Times",size=14,face="plain"), 
                   axis.title.y=element_text(family="Times",size = 14,face="plain"), 
                   axis.title.x=element_text(family="Times",size = 14,face="plain"), 
                   plot.title = element_text(family="Times",size=15,face="bold",hjust = 0.5), 
                   panel.grid.major = element_blank(), 
                   panel.grid.minor = element_blank()) +  scale_x_continuous(limits = c(20,40)) + 
          ggsave(out_tu,width = 12,height = 7)




```






# base substitution types Statistics for Single or Shared SNP Sites
```{r,fig.width=20,fig.height=8}
  library(ggplot2)
  flags = c('single','share','shareAndsingle')  
  for (Flag in flags) {
    
    Freqboxplot_P = "../results/"
    Freqboxplot_F =  paste(Freqboxplot_P,"Sfig1-",Flag, "--SNP-effStat.txt",sep = "")
    Data = read.table(Freqboxplot_F,sep = '\t',header = TRUE)
    baseChange = Data$baseChange	
    eff = Data$eff
    Count = Data$Count
    
    outPictureF =  paste("./outFigures/Sfig1-",Flag,"-SNPbaseSubti.barplot.pdf",sep = "")
    ggplot(Data,aes(x=baseChange,y=Count,fill=eff)) +   
      geom_bar(stat='identity')  + 
      ggtitle(paste(Flag ,"  SNPs ",sep = ""))+ 
      theme_bw()+ 
      theme(legend.position="none",
            axis.text.x=element_text(colour="black",family="Times",size=6,angle = 0, hjust = 1),
            axis.text.y=element_text(family="Times",size=6,face="plain"), 
            axis.title.y=element_text(family="Times",size = 6,face="plain"), 
            axis.title.x=element_text(family="Times",size = 6,face="plain"), 
            plot.title = element_text(family="Times",size=6,face="bold",hjust = 0.5), 
            panel.grid.major = element_blank(), 
            panel.grid.minor = element_blank() ) +
      ylab("No.of SNP") + xlab('')+
      scale_x_discrete(limits=c("C>U","A>G", "G>U", "G>A", "U>C", "C>A", "G>C", "U>G", "C>G", "A>U", "U>A", "A>C"))   
    ggsave(outPictureF,width = 6,height = 3)  
  }



```




